FROM node:20-alpine AS builder

WORKDIR /app

COPY frontend/package*.json ./
RUN npm install

COPY frontend .
RUN npm run build


# ----------------------

FROM nginx:alpine

# ⚠️ remove default nginx config completely
RUN rm -rf /etc/nginx/conf.d/*

# copy YOUR config
COPY nginx/default.conf /etc/nginx/conf.d/default.conf

# copy build
COPY --from=builder /app/build /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]